### ISSUE TITLE
Define BB10 Event API specification

### ISSUE THREAD

**Issue by stranger80** [golemfactory/ya-client#1]
Refactor of Event flow from all Functional APIs into a dedicated Event API.

Event API shall follow the specs as defined [here](https://docs.google.com/document/d/1LWw_4ugMPzRos4FH5LlQmnjHpeLuTvtBiH80ZRLMNDA).

**Comment by stranger80** [comment]
Closing, as REST API redesign has now been implemented.

**Comment by tworec** [comment]
yay! 🥳
