### ISSUE TITLE
url_format! causes compiler warning since 1.64.0

### ISSUE THREAD

**Issue by kamirr** [golemfactory/ya-client#133]
Warning: `named_arguments_used_positionally`
Triggered by: `url_format!("{}", arg);`
Why: Macro expansion changes all arguments into named ones, and Rust warns about positional uses of named macros since 1.64.0.

**Comment by kamirr** [comment]
Workaround commit to revert after a proper fix lands: https://github.com/golemfactory/ya-client/commit/0b5910917154bedfc3efcd4035943f4ef79b9231.

**Comment by mateuszsrebrny** [comment]
try using new format api:
```format!("allocations/{allocation_id}); działa```
