### ISSUE TITLE
define maximum timeout for REST API endpoints

### ISSUE THREAD

**Issue by tworec** [golemfactory/ya-client#76]
https://github.com/golemfactory/ya-client/blob/f7e2c692115b01c81c1652fa14c4ea719035ec72/specs/common.yaml#L14

arose when reviewing
https://github.com/golemfactory/yagna/pull/808/files#diff-ff490246b403bbf6555dcfcf6cb38d31758d138d6fadbe6cd529de60d4374a99R361

**Comment by stranger80** [comment]
Is there any functional reason to limit the timeout value?

**Comment by tworec** [comment]
Yes, server implementation must support maximum possible keep-alive for HTTP connections.
